apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: helloworld
spec:
  containers:
# docker container run -d nginx:alpine
  - name: nginx
    image: nginx:alpine
    ports:
    - name: nginxport
      containerPort: 80
      