kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-ro
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: userjan25-pod-ro
  namespace: default
subjects:
- kind: User
  name: userjan25
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-ro
  apiGroup: rbac.authorization.k8s.io
  